service: sqs-service
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
functions:
  workout:
    handler: handler.workout
    events:
      - http:
          path: workout
          method: get
plugins:
  - serverless-plugin-webpack
custom:
  webpack:
    config: ./../../webpack.config.js
    series: true # run Webpack in series, useful for large projects. Defaults to false.