service: sqs-service
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        # - sqs:DeleteMessage
        # - sqs:ReceiveMessage
      # Resource: arn:aws:sqs:*:*:${self:custom.sqs}
      Resource: arn:aws:sqs:ap-southeast-1:526492987552:demo1	
functions:
  workout:
    handler: handler.workout
    events:
      - http:
          path: workout
          method: post
plugins:
  - serverless-plugin-webpack
custom:
  webpack:
    config: ./../../webpack.config.js
    series: true # run Webpack in series, useful for large projects. Defaults to false.# Welcome to Serverless!
